{% set name = "sexpdata" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sexpdata-{{ version }}.tar.gz
  sha256: e576f62ead32d5041e630f9457d2c1a7544d7fe5dd96a49b55159239115c3773

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - singledispatch

test:
  imports:
    - sexpdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tkf/sexpdata
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: S-expression parser for Python
  description: |
    S-expression parser for Python. sexpdata is a simple S-expression parser/serializer. 
    It has simple `load` and `dump` functions like `pickle`, `json` or `PyYAML`
    module.
  doc_url: http://sexpdata.readthedocs.io/en/latest/
  dev_url: https://github.com/tkf/sexpdata

extra:
  recipe-maintainers:
    - egeogretmen
