travis:
  secure:
    BINSTAR_TOKEN: ZvUaE1pm3GPldgw8VPalJPpOUdYpGXfb98TAYhY4bJMORRfpjRMyPxwrECTZRC5jsE6GN+CxWdUjTiSXfr3fg9KqlbhsF7gcf246dWBaAaPuH9XzZWtaF+f27syIvRtO0PX+cQjqTwSocbDXIjSDDpUUlnUtK+jyVgfAR9VY6tBqzAHEDG0rrpjmfDbBThCu8kbe7+YisUcYXHpMl4Nnc2812+Qtp3vwqHGB5dhTz1zTH8b1lPK1NQoxS9UjzHQoz/oFdjQ1N298FeDf2frcvxtt7OxEJDP4VmhJFRx6qz42ImxpMiJgU9+JJTKNX9ay+ip0vHemRHtDibkRNrLT9tyzLUnxlSDvYn0GAO0CQ8lNZo9EUN80hqdikfGMn8RXUOXwRm69e6zjRSEoseEAQLDEJWpw3VEBtXj/KOxi0zM41pNfzAy2R2b1iOgUr+NzOHqCA4YA6WC+lJehKKUbi0CxqkLcaEiXzva1TDA/k/Gk62BnpmxlGnZshjrXTsqPeMvTMpybwAtpFtiDSLVN/1hEfe+cWnipL784g6xeZabALG3u3eD7iVlKBaRylC9SP/whUL+vlmrGwU8wo548R0XGG7vTSIk5WBFRbRPpxiNpInXRP4fzbeRoeFho6n2zpVhG5rionosVO0V2eKmlTJVwug4Bop894g/6NQagLmE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
