travis:
  secure:
    BINSTAR_TOKEN: vUtK2ujhihJhWrUCWqjEvdou/H5r6i6Rf5Ihy/ZAhboXOSqJefW1mg7NLr+mV5qvGYh9JNL0oX/vNWQk3oB2BFbz94BjXLye8Ywh1yUGPi5BGq4uIdoiZ1ftnZm2VeONnamF61QY7OWZMW00tXSkgS8jZpm5/Vq3icVggyQNXCO3LcUZPa78vufOptdyP3wim6r0ekV8ETy6uU8kHFPkup4IYxJ36x4KF9bXMBLVlIcCfba7OjQ9rJMPHxpYHDjrcsZuG3BpuG6OgsCzeZmd0Au8x3lfPzHNPhOxgJKmMvHYR/LRtkXj6slaQq2mnK8CfiOMK0YVkMMfEsYn+QpnbUqblvnjjkhQSqET57o+ilVz7LPB5dJdWt4eQkwlbi0KuQDfqQDZDti9ZKTawBPljbsNaqjudG/SwMl9+FhMmwbvvtF8ZXQhbuFaOg4fe3HuiGzVV/yySMgxjamlkZLO7l6yrePWyzsQnlQJe1eE1LmzYEJQEs2gs7rWw+dUZuvJVOi3LZN/k5PhRSAuLuaKaejw2fb3cLmRHBGo7zLcLoJLztV3LvBiazzIb6OFWa85lDgW6WsCsfzM0WdChTFsZO3RKNoEIRsL7+2uwS0Tm63ZX3yFDna5Xptgc2ba9qeUZkyiwwiDAwDxwGwfOd0HUyifuo+2Jh3SHQ/kSgLPY+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
